# Generated by Django 5.2.4 on 2026-01-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=150)),
                ('detial_descriptiom', models.TextField(max_length=1000)),
                ('tech_stack', models.CharField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_images/')),
                ('githublink', models.URLField()),
            ],
        ),
    ]
