# Generated by Django 5.2.4 on 2026-01-05 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='githublink',
            new_name='github_link',
        ),
    ]
