# Generated by Django 5.2.4 on 2026-01-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_portfolio', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_name', models.CharField(max_length=30)),
                ('profile_name', models.CharField(max_length=50)),
                ('role', models.CharField(default='Full Stack Web-Developer', max_length=100)),
                ('introduction', models.TextField()),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='profile_img/')),
                ('about_me', models.TextField()),
                ('footer_name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='detial_descriptiom',
            new_name='detialed_descriptiom',
        ),
        migrations.AlterField(
            model_name='projects',
            name='github_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='tech_stack',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='skills',
            name='skill_name',
            field=models.CharField(max_length=200),
        ),
    ]
