# Generated by Django 5.2.4 on 2026-01-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_portfolio', '0005_intro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_pdf',
            field=models.FileField(blank=True, null=True, upload_to='project_pdfs/'),
        ),
    ]
