# Generated by Django 5.2.4 on 2026-01-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_portfolio', '0006_projects_project_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='Category',
            field=models.CharField(default='Backend Developer', max_length=50),
        ),
        migrations.AddField(
            model_name='projects',
            name='status',
            field=models.CharField(default='In Progress', max_length=50),
        ),
    ]
