# Generated by Django 5.2.4 on 2026-01-09 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_portfolio', '0007_projects_category_projects_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=50)),
                ('board', models.CharField(max_length=50)),
                ('institute_name', models.CharField(max_length=100)),
                ('percentage', models.PositiveIntegerField()),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField()),
            ],
        ),
    ]
