# Generated by Django 5.2.4 on 2026-01-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_portfolio', '0008_academicqualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicqualification',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
