# Generated by Django 5.2.4 on 2026-01-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_portfolio', '0009_alter_academicqualification_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_pdf', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('certificate_name', models.CharField(max_length=50)),
            ],
        ),
    ]
