# Generated by Django 5.2.4 on 2026-01-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_portfolio', '0016_result_semester_alter_result_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_number', models.PositiveSmallIntegerField()),
                ('semester_result', models.FileField(blank=True, null=True, upload_to='sem_results/')),
            ],
        ),
    ]
