# Generated by Django 5.2.4 on 2026-01-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_portfolio', '0019_delete_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='intro',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resume_pdf/'),
        ),
    ]
