# Generated by Django 5.2.4 on 2026-01-13 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_portfolio', '0020_intro_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intro',
            old_name='resume',
            new_name='resume_pdf',
        ),
    ]
