# Generated by Django 5.2.4 on 2026-01-15 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_portfolio', '0022_keyfeature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='detialed_descriptiom',
            new_name='detialed_description',
        ),
        migrations.AddField(
            model_name='semester',
            name='qualification',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='My_portfolio.academicqualification'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='visitor_email',
            field=models.EmailField(max_length=254),
        ),
    ]
