# Generated by Django 5.2.4 on 2026-01-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_portfolio', '0023_rename_detialed_descriptiom_projects_detialed_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='icon',
            field=models.CharField(max_length=50),
        ),
    ]
