# Generated by Django 5.2.4 on 2026-01-24 10:18

import My_portfolio.storages
import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_portfolio', '0024_alter_skills_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedIn', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('whatsapp', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='intro',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, storage=My_portfolio.storages.ImageStorage(), upload_to='profile_img/'),
        ),
        migrations.AlterField(
            model_name='intro',
            name='resume_pdf',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=My_portfolio.storages.ImageStorage(), upload_to='project_image/'),
        ),
    ]
