# Generated by Django 5.2.4 on 2026-01-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_portfolio', '0026_remove_semester_semester_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
