# Generated by Django 5.2.4 on 2026-01-25 04:56

import My_portfolio.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_portfolio', '0027_semester_cgpa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intro',
            name='resume_pdf',
        ),
        migrations.AddField(
            model_name='intro',
            name='resume_img',
            field=models.ImageField(blank=True, null=True, storage=My_portfolio.storages.ImageStorage(), upload_to='resume_img/'),
        ),
    ]
